---
github_runner_enabled: true
github_runner_url: "https://github.com/your-org"

github_runner_name: "{{ inventory_hostname }}"
github_runner_labels:
  - self-hosted
  - linux
  - ubuntu
  - hetzner
github_runner_runnergroup: ""
